#!/usr/bin/env bash
set -euo pipefail

base_phase=${1:?baseline phase path is required}
candidate_bundle=${2:?delta-forge candidate bundle path is required}
output=${3:?candidate phase output path is required}

test -f "$base_phase"
test -f "$candidate_bundle"
grep -q 'activity NormalizeSource(SourceGraph) -> SemanticIR' "$base_phase"

jq -e '
  .schema == "gooo/language-delta-forge/candidate-bundle/v1" and
  .decision == "CLOSED" and
  .counts == {added_cells:2,retired_cells:1,split_cells:1} and
  .semantic_graph_delta.exact_pair == true and
  .rollback_delta.exact_pair == true and
  (.semantic_graph_delta.added_cells | map(.id) | sort) == [
    "cell.normalize-source.parse-source",
    "cell.normalize-source.validate-stable-ids"
  ] and
  (.semantic_graph_delta.retired_cells | map(.id)) == ["cell.normalize-source.coarse"] and
  (.semantic_graph_delta.split_cells | map(.split_id)) == ["split.normalize-source.coarse"] and
  (.rollback_delta.remove_added_cell_ids | sort) == [
    "cell.normalize-source.parse-source",
    "cell.normalize-source.validate-stable-ids"
  ]
' "$candidate_bundle" >/dev/null

bundle_digest=$(sha256sum "$candidate_bundle" | awk '{print "sha256:" $1}')
candidate_digest=$(jq -r '.candidate_digest' "$candidate_bundle")
delta_digest=$(jq -r '.delta_digest' "$candidate_bundle")
retired_cell=$(jq -r '.semantic_graph_delta.retired_cells[0].id' "$candidate_bundle")
added_cell_one=$(jq -r '.semantic_graph_delta.added_cells[0].id' "$candidate_bundle")
added_cell_two=$(jq -r '.semantic_graph_delta.added_cells[1].id' "$candidate_bundle")
test "$bundle_digest" = "sha256:49244a778d6e80c67bb5fb0b99342873ba987916b14febb500524a26a5af3490"
test "$candidate_digest" = "sha256:4edd900ea94b1cb461b27d61fb06e72993424eb8ad424b82ac19b78b59318bdb"
test "$delta_digest" = "sha256:826a90daaf19fb0f0b0b51af89c53150219ca624331905a4c913e329b085a6e6"
test "$retired_cell" = "cell.normalize-source.coarse"
test "$added_cell_one" = "cell.normalize-source.parse-source"
test "$added_cell_two" = "cell.normalize-source.validate-stable-ids"

mkdir -p "$(dirname "$output")"
{
	printf '%s\n' 'package reflexive'
	printf '%s\n' 'namespace reflexive'
	printf '%s\n' ''
	printf '%s\n' 'entity SourceGraph id "gooo://reflexive/compiler/source-graph"'
	printf '%s\n' 'entity ParsedSource id "gooo://reflexive/compiler/parsed-source"'
	printf '%s\n' 'entity SemanticIR id "gooo://reflexive/compiler/semantic-ir"'
	printf '%s\n' 'entity GeneratedBackend id "gooo://reflexive/compiler/generated-backend"'
	printf '%s\n' 'entity Evidence id "gooo://reflexive/compiler/evidence"'
	printf '%s\n' ''
	printf '# Generated by scripts/apply-split-candidate.sh from the immutable Gooo delta-forge bundle.\n'
	printf '# candidate_digest=%s bundle_digest=%s delta_digest=%s\n' "$candidate_digest" "$bundle_digest" "$delta_digest"
	printf '# retired_cell=%s added_cells=%s+%s\n' "$retired_cell" "$added_cell_one" "$added_cell_two"
	printf '%s\n' '# topology reflexive.normalize.v2'
	printf '%s\n' '# precedence REFUTED > UNKNOWN > CLOSED'
	printf '%s\n' '# acceptance CLOSED UNKNOWN REFUTED'
	printf '%s\n' '# rollback RETAIN_BASELINE'
	printf '%s\n' '# authority SOURCE_GOOO_GRAPH'
	printf '%s\n' '# split NormalizeSource -> ParseSource + ValidateStableIDs'
	printf '%s\n' '# edge ParseSource -> ValidateStableIDs : ParsedSource'
	printf '%s\n' '# edge ValidateStableIDs -> EmitBackend : SemanticIR'
	printf '%s\n' '# edge ValidateStableIDs -> VerifyReplay : SemanticIR'
	printf '%s\n' ''
	printf '%s\n' 'activity ParseSource(SourceGraph) -> ParsedSource computes "reflexive.normalize:v1;input=GOOO;declarations=entity,activity;stable_id=declared-or-namespace-activity-name;normal_form=sort-by-stable-id;duplicate=REFUTED;missing=UNKNOWN;required_entity=gooo://reflexive/input/required;split=ParseSource+ValidateStableIDs"'
	printf '%s\n' 'activity ValidateStableIDs(ParsedSource) -> SemanticIR computes "reflexive.validate-stable-ids:v1;input=PARSED_SOURCE;duplicate=REFUTED;missing=UNKNOWN"'
	printf '%s\n' 'activity EmitBackend(SemanticIR) -> GeneratedBackend computes "reflexive.backend-go:v1;authority=SOURCE_GOOO_GRAPH;artifact=BACKEND_ONLY;binding=semantic-ir"'
	printf '%s\n' 'activity VerifyReplay(SemanticIR) -> Evidence computes "reflexive.replay:v1;input=GENERATED_SEMANTIC_IR;compare=CANONICAL_DIGEST;rollback=RETAIN_BASELINE"'
} > "$output"
